# Generated by Django 3.1.7 on 2021-05-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('superficie', models.IntegerField()),
                ('direccion', models.CharField(max_length=250)),
                ('habitaciones', models.IntegerField()),
                ('baños', models.IntegerField()),
                ('otras_caracteristicas', models.TextField()),
            ],
        ),
    ]
