# Generated by Django 3.1.7 on 2021-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0003_auto_20210525_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_oferta',
            field=models.CharField(max_length=20),
        ),
    ]
