# Generated by Django 3.1.7 on 2021-05-27 17:40

from django.db import migrations, models
import django.db.models.deletion
import smarthome.models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0004_auto_20210527_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=smarthome.models.get_image_filename, verbose_name='Image')),
                ('inmueble', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='smarthome.inmueble')),
            ],
        ),
        migrations.DeleteModel(
            name='AlbumImagenes',
        ),
    ]
