# Generated by Django 3.1.7 on 2021-05-28 00:51

from django.db import migrations, models
import smarthome.models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0008_auto_20210527_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='inmuebles_images/no-img.jpg', upload_to=smarthome.models.get_image_filename, verbose_name='Image'),
        ),
    ]
