# Generated by Django 3.1.7 on 2021-06-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0010_auto_20210603_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='propietario',
            field=models.CharField(max_length=150),
        ),
    ]
