# Generated by Django 3.1.7 on 2021-06-04 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smarthome', '0012_auto_20210603_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='favorito',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
